#!/bin/bash

# Display big warning and fix options

clear

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║            🚨 BROWSER EXTENSION ERROR DETECTED 🚨              ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "  Error: Unauthorized request from chrome-extension://..."
echo ""
echo "  This happens when React DevTools or similar extensions"
echo "  try to intercept Expo dev server requests."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  ⚡ INSTANT FIXES (Pick Any):"
echo ""
echo "  1️⃣  INCOGNITO MODE (Recommended - 10 seconds)"
echo "     → Press Ctrl+Shift+N (or Cmd+Shift+N on Mac)"
echo "     → Go to: http://localhost:8081"
echo "     → Done! ✅"
echo ""
echo "  2️⃣  RESTART SERVER (Permanent fix - 30 seconds)"
echo "     → Press Ctrl+C to stop server"
echo "     → Run: npm run start:clear"
echo "     → Done! ✅"
echo ""
echo "  3️⃣  DISABLE EXTENSION (If you prefer - 1 minute)"
echo "     → Go to: chrome://extensions/"
echo "     → Turn off React Developer Tools"
echo "     → Refresh page"
echo "     → Done! ✅"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  📚 More Info:"
echo "  → Read: FIX_NOW.md (quick guide)"
echo "  → Read: BROWSER_EXTENSION_FIX.md (detailed guide)"
echo "  → Run: ./fix-extension-error.sh (interactive helper)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  💡 QUICK TIP:"
echo "  I've created metro.config.js to fix this permanently."
echo "  Just restart your server and it should work!"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""

read -p "  Press Enter to open incognito instructions, or Ctrl+C to exit..."

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  🕵️  INCOGNITO MODE STEP-BY-STEP:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  1. Keep your current terminal running"
echo "     (Don't close this or stop the server!)"
echo ""
echo "  2. Open a new incognito window:"
echo ""
if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "     → Press: Cmd+Shift+N"
else
    echo "     → Press: Ctrl+Shift+N"
fi
echo ""
echo "  3. In the incognito window, go to:"
echo ""
echo "     http://localhost:8081"
echo ""
echo "  4. Your app should load without errors! ✅"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  That's it! Your app should work now."
echo ""
echo "  If you still see errors, try:"
echo "  → npm run start:clear (restart server)"
echo "  → Read FIX_NOW.md for more options"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
